---
- name: Create directory if it doesn't already exist
  ansible.builtin.file:
    path: "{{ cfg_dir }}"
    state: directory
    mode: '0755'
    group: ansible
    owner: ansible

- name: Check that the config file doesn't already exist
  ansible.builtin.stat:
    path: "{{ cfg_file }}"
  register: stat_result

# Generate Machine Configurations. This is using the qemu agent as per: https://www.talos.dev/v1.7/talos-guides/install/virtualized-platforms/proxmox/
- name: Generate machine configurations controlplane.yaml, worker.yaml, and talosconfig
  when: "not stat_result.stat.exists"
  ansible.builtin.command:
    cmd: "{{ talos_cmd }} https://{{ cp_ip }}:6443 --output-dir {{ cfg_dir }} --install-image {{ talos_install_image }}:{{ talos_version }}"
  changed_when: true
