---
# Generate Machine Configurations. This is using the qemu agent as per: https://www.talos.dev/v1.7/talos-guides/install/virtualized-platforms/proxmox/
- name: Show all the worker nodes
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop:
    - "{{ worker_1 }}"
    - "{{ worker_2 }}"
  # loop: "{{ query('inventory_hostnames', 'agents') }}"

- name: Apply config to worker nodes
  ansible.builtin.command:
    cmd: "{{ talos_bin }} apply-config --insecure --nodes {{ item }} --file {{ cfg_dir }}/worker.yaml"
  loop:
    - "{{ worker_1 }}"
    - "{{ worker_2 }}"
  changed_when: true
