---
# Generate Machine Configurations. This is using the qemu agent as per: https://www.talos.dev/v1.7/talos-guides/install/virtualized-platforms/proxmox/
- name: Apply config to first controlplane node
  ansible.builtin.command:
    cmd: talosctl apply-config --insecure --nodes {{ cp_ip }} --file {{ cfg_dir }}/controlplane.yaml
  changed_when: true

- name: Apply config the other controlplanes
  ansible.builtin.command:
    cmd: talosctl apply-config --insecure --nodes {{ item }} --file {{ cfg_dir }}/controlplane.yaml
  loop: "{{ controlplanes }}"
  changed_when: true

# - name: Apply config to third node
#   ansible.builtin.command:
#     cmd: talosctl apply-config --insecure --nodes {{ cp_3 }} --file {{ cfg_dir }}/controlplane.yaml
#   changed_when: true
