---
# Apply config to the control plane nodes
- name: Apply config to first control plane node
  ansible.builtin.command:
    cmd: "{{ talos_bin }} apply-config --insecure --nodes {{ cp_ip }} --file {{ cfg_dir }}/controlplane.yaml"
  changed_when: true

- name: Apply config to the other control plane nodes
  ansible.builtin.command:
    cmd: "{{ talos_bin }} apply-config --insecure --nodes {{ item }} --file {{ cfg_dir }}/controlplane.yaml"
  loop:
    - "{{ cp_1 }}"
    - "{{ cp_2 }}"
  changed_when: true
